# Generated by Django 5.1.6 on 2026-05-20 12:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        default="",
                        max_length=255,
                        verbose_name="оригинальное имя файла",
                    ),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(verbose_name="размер файла (байты)"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата загрузки"
                    ),
                ),
                (
                    "last_downloaded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="последнее скачивание"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="комментарий"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        default="",
                        max_length=500,
                        verbose_name="путь к файлу в хранилище",
                    ),
                ),
                (
                    "special_link",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="специальная ссылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
